# Beads Workers Configuration File
# This file demonstrates the available configuration options for beads-workers
# Priority order: CLI flags > Environment variables > Config file > Defaults

# Maximum number of concurrent workers (default: number of CPUs)
max_workers: 4

# Path to beads database (default: .beads/beads.db)
# db_path: /path/to/beads.db

# Path to beads JSONL file (default: .beads/issues.jsonl)
# jsonl_path: /path/to/issues.jsonl

# Default timeout for tasks in seconds (default: 300)
default_timeout: 300

# Retry configuration
retry:
  # Maximum number of retries for failed tasks (default: 3)
  max_retries: 3

  # Initial backoff duration in seconds (default: 1)
  initial_backoff_secs: 1

  # Maximum backoff duration in seconds (default: 60)
  max_backoff_secs: 60

  # Backoff multiplier (default: 2.0)
  backoff_multiplier: 2.0

# Logging configuration
logging:
  # Log level: trace, debug, info, warn, error (default: info)
  level: info

  # Log format: pretty, json, compact (default: pretty)
  format: pretty

  # Log file path (optional)
  # file: /var/log/beads-workers.log

  # Enable ANSI colors (default: true)
  colors: true

# IPC configuration
ipc:
  # Socket path for IPC communication (default: .beads/beads-workers.sock)
  # socket_path: /tmp/beads-workers.sock

  # Enable IPC server (default: true)
  enabled: true

  # Connection timeout in seconds (default: 30)
  timeout_secs: 30

# Worker configuration
worker:
  # Poll interval in milliseconds (default: 100)
  poll_interval_ms: 100

  # Maximum task queue size per worker (default: 1000)
  queue_size: 1000

  # Enable task prefetching (default: true)
  prefetch: true

  # Number of tasks to prefetch (default: 10)
  prefetch_count: 10

  # Graceful shutdown timeout in seconds (default: 30)
  shutdown_timeout_secs: 30

# Environment Variable Overrides:
# All config options can be overridden with environment variables:
#
# Core settings:
#   BEADS_MAX_WORKERS=8
#   BEADS_DB_PATH=/path/to/db
#   BEADS_JSONL_PATH=/path/to/jsonl
#   BEADS_DEFAULT_TIMEOUT=600
#
# Retry settings:
#   BEADS_MAX_RETRIES=5
#   BEADS_INITIAL_BACKOFF_SECS=2
#   BEADS_MAX_BACKOFF_SECS=120
#   BEADS_BACKOFF_MULTIPLIER=2.5
#
# Logging settings:
#   BEADS_LOG_LEVEL=debug
#   BEADS_LOG_FORMAT=json
#   BEADS_LOG_FILE=/var/log/beads.log
#   BEADS_LOG_COLORS=false
#
# IPC settings:
#   BEADS_IPC_SOCKET_PATH=/tmp/custom.sock
#   BEADS_IPC_ENABLED=true
#   BEADS_IPC_TIMEOUT_SECS=60
#
# Worker settings:
#   BEADS_WORKER_POLL_INTERVAL_MS=200
#   BEADS_WORKER_QUEUE_SIZE=2000
#   BEADS_WORKER_PREFETCH=true
#   BEADS_WORKER_PREFETCH_COUNT=20
#   BEADS_WORKER_SHUTDOWN_TIMEOUT_SECS=60

# CLI Flag Overrides:
# CLI flags have the highest priority:
#
#   --config PATH              Custom config file path
#   --beads-dir PATH           Beads directory
#   -j, --max-workers N        Maximum concurrent workers
#   -v, --verbose              Enable verbose logging (trace)
#   -d, --debug                Enable debug logging
#   --log-level LEVEL          Explicit log level
